name: Ansible Playbook

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.ANSIBLE_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i inventory playbook.yaml
      env:
        ANSIBLE_HOST: ${{ secrets.ANSIBLE_HOST }}
        ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}
